# PyTorch Fundamentals 🚀

This notebook is organized for beginners learning PyTorch.

## Topics
- Importing PyTorch
- Scalars, Vectors, Matrices, and Tensors
- Tensor Dimensions (`ndim`)
- Tensor Shapes (`shape`)
- Creating Random Tensors
- Tensor Datatypes
- Basic Tensor Operations

**Goal:** Build a strong foundation before studying neural networks and deep learning.


## Environment Setup

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Tensors

In [3]:
#creating tensor such as scaler
scaler = torch.tensor(7)
scaler
#pytorch tensotr are created using torch.tensor


tensor(7)

In [4]:
scaler.ndim

0

In [5]:
#getr tensor back as python int
scaler.item()
scaler.shape

torch.Size([])

## Vectors

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

## Matrices

In [9]:
matrix  = torch.tensor([[7,8],
                        [6,5]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,5,6],
                        [3,6,6,7],
                        [3,6,6,7],
                        [3,6,6,7]]])


In [13]:
TENSOR.shape

torch.Size([1, 4, 4])

## Random Tensors

In [14]:
### random tensor
#why random tensor
#its imp because wau nn learns they start with random numbers
# 1start with random numb
# look data , update , look at data , update


In [15]:
#create random tensor
random_tens = torch.rand(1,2,4)
random_tens

tensor([[[0.2731, 0.6197, 0.9673, 0.9587],
         [0.5108, 0.2008, 0.8830, 0.4745]]])

In [16]:
#create rand tensor with similar image tensor
rand_img_tensor = torch.rand(size=(224,224,3))
rand_img_tensor.shape,rand_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
#zeros and  ones


In [18]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,3))

In [19]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,3))

In [21]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
#create a range of tensors
#use torch.range

In [24]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#another way
zero_to_1k=torch.arange(start=0,end=1000,step=70)
zero_to_1k

tensor([  0,  70, 140, 210, 280, 350, 420, 490, 560, 630, 700, 770, 840, 910,
        980])

In [26]:

#creating tensor like
some_zeros= torch.zeros_like(zero_to_1k)
some_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
 #tensor data types
float_32_tensor = torch.tensor([3.0,2,5.0,0.3],
                               dtype=None)
float_32_tensor

tensor([3.0000, 2.0000, 5.0000, 0.3000])

In [28]:
#because it is default flaot
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.0000, 2.0000, 5.0000, 0.3000], dtype=torch.float16)

In [30]:
float_32_tensor*float_16_tensor

tensor([ 9.0000,  4.0000, 25.0000,  0.0900])

In [31]:
#create a tensor
s_t = torch.rand(3,4)

In [32]:
s_t

tensor([[0.1526, 0.8004, 0.0650, 0.3395],
        [0.9600, 0.8095, 0.7620, 0.0017],
        [0.2604, 0.8107, 0.0967, 0.1314]])

In [33]:
print(s_t)

tensor([[0.1526, 0.8004, 0.0650, 0.3395],
        [0.9600, 0.8095, 0.7620, 0.0017],
        [0.2604, 0.8107, 0.0967, 0.1314]])


In [34]:
print(f"datatype of tensor:{s_t.dtype}")
print(f"shape of tensor:{s_t.shape}")
print(f"size of tensor:{s_t.size()}")
print(f"device tensor is on:{s_t.device}")

datatype of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
size of tensor:torch.Size([3, 4])
device tensor is on:cpu


In [35]:
#manipulating tensor
#addition
#subtraction
#multplicationg
#divison
#matrix


In [36]:
#create a tensor
a_t = torch.tensor([1,2,3])
a_t+10

tensor([11, 12, 13])

In [37]:
#multlply
a_t*10

tensor([10, 20, 30])

In [38]:
##mattrix  multiplication
torch.matmul(a_t,a_t)

tensor(14)

In [40]:
#findind min and max , sum , etc
x  = torch.arange(0,100,10)
x_f = torch.


In [41]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
torch.min(x)

tensor(0)

In [43]:
torch.max(x)

tensor(90)

In [44]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [45]:
#now reshaping a tensor
x_reshaped = x.reshape(10,1)
x_reshaped

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [47]:
#view
z = x.view(1,10)

In [48]:
z

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [49]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>